# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LhJvLVPwlKP7LmlnCCAaI9382ZmkXi2e
"""

!pip install pymupdf

# ------------------ Importing Libraries ------------------
import fitz
import os, json, re
from datetime import datetime
from google.colab import files
from IPython.display import HTML
from IPython.display import display

# ------------------ Config ------------------
CONFIG_JSON = {
    "upload_directory": "uploads",
    # Combined ICD-10 and ICD-9 pattern
    "icd_pattern": r"(ICD-(?:10|9)-CM):?\s*\[?([A-Z\d]\d{1,2}(?:\.\d+)?(?:,\s*[\s]*[A-Z\d]\d{1,2}(?:\.\d+)?)*)\]?"
}

UPLOAD_DIR = CONFIG_JSON["upload_directory"]
os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs("logs", exist_ok=True)
# Save as JSON file
with open("config.json", "w") as f:
    json.dump(CONFIG_JSON, f, indent=4)

# ------------------ Logging ------------------
def log(msg):
    logfile = "logs/app.log"
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(logfile, "a") as f:
        f.write(f"[{timestamp}] {msg}\n")

# ------------------ Upload PDF ------------------
uploaded = files.upload()
pdf_path = list(uploaded.keys())[0]
log(f"Uploaded PDF: {pdf_path}")

# ------------------ Extract ICD codes + words + Highlight PDF ------------------
def extract_and_highlight(pdf_path, config):
    doc = fitz.open(pdf_path)
    icd_regex = re.compile(config["icd_pattern"], re.IGNORECASE)

    pdf_data = []

    for page_num, page in enumerate(doc):
        text = page.get_text("text")
        page_icd_data = []
        words_data = []

        # ---- Extract ICD codes (no coordinates) + highlight in PDF ----
        for match in icd_regex.finditer(text):
            icd_prefix = match.group(1).upper()
            icd_block = match.group(2)

            codes = [c.strip() for c in icd_block.split(",") if c.strip()]

            for code in codes:
                page_icd_data.append(code)

                # Highlight in PDF
                if "ICD-10" in icd_prefix:
                    color_stroke, color_fill = (1, 0, 0), (1, 0.6, 0.6)  # RED
                else:
                    color_stroke, color_fill = (0, 0, 1), (0.6, 0.7, 1)  # BLUE

                instances = page.search_for(code, quads=True)
                for inst in instances:
                    annot = page.add_highlight_annot(inst.rect)
                    annot.set_colors(stroke=color_stroke)  # Only stroke color
                    annot.set_opacity(0.40)
                    annot.update()

        # ---- Extract all words + coordinates ----
        for w in page.get_text("words"):
            words_data.append({
                "text": w[4],
                "x0": round(w[0], 2),
                "y0": round(w[1], 2),
                "x1": round(w[2], 2),
                "y1": round(w[3], 2)
            })

        pdf_data.append({
            "page_number": page_num + 1,
            "extracted_icd_codes": page_icd_data,
            "words": words_data,
            "text_sample": text[:150]
        })

    # ---- Save highlighted PDF ----
    base_name = pdf_path.rsplit(".", 1)[0]
    highlighted_pdf = f"{base_name}_highlighted.pdf"
    doc.save(highlighted_pdf)
    doc.close()
    log(f"Highlighted PDF saved: {highlighted_pdf}")

    # ---- Save JSON ----
    json_file = f"{base_name}_icd_words.json"
    with open(json_file, "w") as f:
        json.dump(pdf_data, f, indent=4)
    log(f"ICD + Words JSON saved: {json_file}")

    return highlighted_pdf, json_file

# ------------------ Run extraction & highlight ------------------
highlighted_pdf, json_file = extract_and_highlight(pdf_path, CONFIG_JSON)

# ------------------ Automatic download ------------------
files.download(highlighted_pdf)
files.download(json_file)
print("✅ Highlighted PDF and ICD + Words JSON ready for download!")

# ------------------ Manual download button ------------------
def create_download_button(file_path, button_text="Download File"):
    import base64
    with open(file_path, "rb") as f:
        data = f.read()
    b64 = base64.b64encode(data).decode()
    ext = os.path.splitext(file_path)[1].lower()
    mime = "application/pdf" if ext == ".pdf" else "application/json"
    href = f'<a download="{os.path.basename(file_path)}" href="data:{mime};base64,{b64}" target="_blank"><button>{button_text}</button></a>'
    return HTML(href)

# Display both download buttons
display(create_download_button(highlighted_pdf, button_text="Download Highlighted PDF"))
display(create_download_button(json_file, button_text="Download ICD + Words JSON"))

